server:
  port: 8091
spring:
  datasource:
    dynamic:
      primary: bs-mes
      strict: true
      datasource:
        bs-mes:
          url: jdbc:oracle:thin:@//10.2.0.130/BSMES
          username: mesprod
          password: bsmes2019
          driver-class-name: oracle.jdbc.OracleDriver
          druid:
            initial-size: 1
            min-idle: 1
            max-active: 2
            max-wait: 60000
        bs-machine1:
          url: jdbc:sqlserver://10.2.3.233;DatabaseName=BS5GW
          username: sa
          password: longi
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          druid:
            initial-size: 0
            min-idle: 2
            max-active: 5
            max-wait: 60000
        bs-machine2:
          url: jdbc:sqlserver://10.2.11.50;DatabaseName=BS5GW
          username: sa
          password: longi
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          druid:
            initial-size: 0
            min-idle: 2
            max-active: 5
            max-wait: 60000
        bs-machine3:
          url: jdbc:sqlserver://10.2.26.10;DatabaseName=BS5GW
          username: sa
          password: longi
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          druid:
            initial-size: 0
            min-idle: 2
            max-active: 5
            max-wait: 60000
        tc-mes:
          url: jdbc:oracle:thin:@//10.2.64.155/tcmes
          username: TCMES
          password: tc2021MESLongi
          driver-class-name: oracle.jdbc.OracleDriver
          druid:
            initial-size: 1
            min-idle: 1
            max-active: 2
            max-wait: 60000
        tc-machine1:
          url: jdbc:sqlserver://10.2.66.10;DatabaseName=TC10GW
          username: sa
          password: longi
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          druid:
            initial-size: 0
            min-idle: 2
            max-active: 5
            max-wait: 60000
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapping/**/*.xml