server:
  port: 8090
spring:
  web:
    resources:
      static-locations: file:C:\spring\report\static
  datasource:
    druid:
      # 监控配置
      stat-view-servlet:
        login-username: admin                       # 登录账号
        login-password: 123456                      # 登录密码
        reset-enable: false                         # 重置监控页面数据
        url-pattern: /druid/*                       # 登录页面后缀
        enabled: true                               # 开启监控
        allow:                                      # 添加IP白名单,不写就是所有都允许
      # 监控配置中的 web监控
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        enabled: true
    dynamic:
      primary: config
      strict: true
      datasource:
        config:
          url: jdbc:oracle:thin:@//10.2.0.130/BSMES
          username: mesprod
          password: bsmes2019
          driver-class-name: oracle.jdbc.OracleDriver
          druid:
            initial-size: 0
            min-idle: 0
            max-active: 2
            max-wait: 60000
        bs-dg:
          url: jdbc:oracle:thin:@//10.2.64.185/BSMES
          username: mesprod
          password: bsmes2019
          driver-class-name: oracle.jdbc.OracleDriver
          druid:
            initial-size: 0
            min-idle: 2
            max-active: 5
            max-wait: 60000
        bs-scada:
          url: jdbc:oracle:thin:@//10.2.0.149/BSSCADA
          username: MESSCADA
          password: RD_dev#BSsca@401
          driver-class-name: oracle.jdbc.OracleDriver
          druid:
            initial-size: 0
            min-idle: 1
            max-active: 5
            max-wait: 60000
        tc-dg:
          url: jdbc:oracle:thin:@//10.2.0.165:1521/tcmes
          username: TCMES
          password: tc2021MESLongi
          driver-class-name: oracle.jdbc.OracleDriver
          druid:
            initial-size: 0
            min-idle: 2
            max-active: 5
            max-wait: 60000
        tc-scada:
          url: jdbc:oracle:thin:@//10.2.64.143/TCSCADA
          username: TCSCADA
          password: RD_dev#TCsca@401
          driver-class-name: oracle.jdbc.OracleDriver
          druid:
            initial-size: 0
            min-idle: 1
            max-active: 5
            max-wait: 60000
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapping/**/*.xml